name: auto squash
on: 
  issue_comment:
    types: [created]
jobs:
  squash:
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/squash'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3.1.0
      id: get_pull_req_branch
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const response = await github.pulls.get({
            pull_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          console.log(response);
          core.setOutput('HEAD_REF', response.data.head.ref);
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: "${{ steps.get_pull_req_branch.HEAD_REF }}"
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - run: ./.github/squash.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
